/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CustomActivity {
    id: bigint;
    name: string;
    suggestedItems: Array<SuggestedItem>;
}
export interface Trip {
    id: bigint;
    latitude: number;
    destination: string;
    endDate: bigint;
    createdAt: bigint;
    activities: Array<string>;
    longitude: number;
    startDate: bigint;
}
export interface CustomCategory {
    id: bigint;
    name: string;
}
export interface TemplateView {
    id: bigint;
    name: string;
    createdAt: bigint;
    itemCount: bigint;
    activities: Array<string>;
    description: string;
    bagCount: bigint;
}
export interface Bag {
    id: bigint;
    name: string;
    weightLimit?: bigint;
    listId: bigint;
}
export interface SuggestedItem {
    name: string;
    quantity: bigint;
    category: string;
}
export interface CachedWeatherDay {
    date: string;
    tempMax: number;
    tempMin: number;
    isHistorical: boolean;
    weatherCode: bigint;
    precipitationSum?: number;
    precipitationProbability?: number;
}
export type BagFilter = {
    __kind__: "all";
    all: null;
} | {
    __kind__: "specific";
    specific: bigint;
} | {
    __kind__: "unassigned";
    unassigned: null;
};
export interface CachedTripWeather {
    days: Array<CachedWeatherDay>;
    tripId: bigint;
    cachedAt: bigint;
    hasHistoricalDays: boolean;
}
export interface UserProfile {
    name: string;
}
export interface PackingItem {
    id: bigint;
    weight?: bigint;
    name: string;
    quantity: bigint;
    category: string;
    bagId?: bigint;
    packed: boolean;
    listId: bigint;
}
export interface backendInterface {
    addItem(listId: bigint, name: string, category: string, quantity: bigint, weight: bigint | null, bagId: bigint | null): Promise<bigint>;
    applyTemplate(tripId: bigint, templateId: bigint): Promise<void>;
    assignToBag(itemId: bigint, bagId: bigint | null): Promise<void>;
    bulkAddItems(listId: bigint, newItems: Array<{
        weight?: bigint;
        name: string;
        quantity: bigint;
        category: string;
    }>): Promise<Array<bigint>>;
    clearTripWeather(tripId: bigint): Promise<void>;
    createBag(listId: bigint, name: string, weightLimit: bigint | null): Promise<bigint>;
    createCustomActivity(name: string, suggestedItems: Array<SuggestedItem>): Promise<bigint>;
    createCustomCategory(name: string): Promise<bigint>;
    createTemplate(name: string, description: string, activities: Array<string>): Promise<bigint>;
    createTrip(destination: string, latitude: number, longitude: number, startDate: bigint, endDate: bigint, activities: Array<string>): Promise<bigint>;
    deleteBag(id: bigint): Promise<void>;
    deleteCustomActivity(id: bigint): Promise<void>;
    deleteCustomCategory(id: bigint): Promise<void>;
    deleteItem(id: bigint): Promise<void>;
    deleteTemplate(id: bigint): Promise<void>;
    deleteTrip(id: bigint): Promise<void>;
    getActivitySuggestedItems(activityIds: Array<bigint>): Promise<Array<SuggestedItem>>;
    getBags(listId: bigint): Promise<Array<Bag>>;
    getCustomActivities(): Promise<Array<CustomActivity>>;
    getCustomCategories(): Promise<Array<CustomCategory>>;
    getItems(listId: bigint, packedFilter: boolean | null, bagFilter: BagFilter): Promise<Array<PackingItem>>;
    getProfile(): Promise<UserProfile | null>;
    getTemplateById(id: bigint): Promise<TemplateView | null>;
    getTemplates(): Promise<Array<TemplateView>>;
    getTripById(id: bigint): Promise<Trip | null>;
    getTripWeather(tripId: bigint): Promise<CachedTripWeather | null>;
    getTrips(): Promise<Array<Trip>>;
    saveAsTemplate(tripId: bigint, name: string, description: string): Promise<bigint>;
    setProfile(name: string): Promise<void>;
    setTripWeather(tripId: bigint, days: Array<CachedWeatherDay>, hasHistoricalDays: boolean): Promise<void>;
    togglePacked(id: bigint): Promise<boolean>;
    updateBag(id: bigint, name: string, weightLimit: bigint | null): Promise<void>;
    updateCustomActivity(id: bigint, name: string, suggestedItems: Array<SuggestedItem>): Promise<void>;
    updateCustomCategory(id: bigint, name: string): Promise<void>;
    updateItem(id: bigint, name: string, category: string, quantity: bigint, weight: bigint | null, bagId: bigint | null): Promise<void>;
    updateTemplate(id: bigint, name: string, description: string, activities: Array<string>): Promise<void>;
    updateTrip(id: bigint, destination: string, latitude: number, longitude: number, startDate: bigint, endDate: bigint, activities: Array<string>): Promise<void>;
}
import type { Bag as _Bag, BagFilter as _BagFilter, CachedTripWeather as _CachedTripWeather, CachedWeatherDay as _CachedWeatherDay, PackingItem as _PackingItem, TemplateView as _TemplateView, Trip as _Trip, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addItem(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: bigint | null, arg5: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addItem(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addItem(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async applyTemplate(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.applyTemplate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyTemplate(arg0, arg1);
            return result;
        }
    }
    async assignToBag(arg0: bigint, arg1: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignToBag(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignToBag(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bulkAddItems(arg0: bigint, arg1: Array<{
        weight?: bigint;
        name: string;
        quantity: bigint;
        category: string;
    }>): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkAddItems(arg0, to_candid_vec_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkAddItems(arg0, to_candid_vec_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearTripWeather(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearTripWeather(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearTripWeather(arg0);
            return result;
        }
    }
    async createBag(arg0: bigint, arg1: string, arg2: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBag(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBag(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async createCustomActivity(arg0: string, arg1: Array<SuggestedItem>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomActivity(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomActivity(arg0, arg1);
            return result;
        }
    }
    async createCustomCategory(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomCategory(arg0);
            return result;
        }
    }
    async createTemplate(arg0: string, arg1: string, arg2: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTemplate(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTemplate(arg0, arg1, arg2);
            return result;
        }
    }
    async createTrip(arg0: string, arg1: number, arg2: number, arg3: bigint, arg4: bigint, arg5: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTrip(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTrip(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async deleteBag(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBag(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBag(arg0);
            return result;
        }
    }
    async deleteCustomActivity(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomActivity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomActivity(arg0);
            return result;
        }
    }
    async deleteCustomCategory(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomCategory(arg0);
            return result;
        }
    }
    async deleteItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteItem(arg0);
            return result;
        }
    }
    async deleteTemplate(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTemplate(arg0);
            return result;
        }
    }
    async deleteTrip(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTrip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTrip(arg0);
            return result;
        }
    }
    async getActivitySuggestedItems(arg0: Array<bigint>): Promise<Array<SuggestedItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivitySuggestedItems(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivitySuggestedItems(arg0);
            return result;
        }
    }
    async getBags(arg0: bigint): Promise<Array<Bag>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBags(arg0);
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBags(arg0);
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomActivities(): Promise<Array<CustomActivity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomActivities();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomActivities();
            return result;
        }
    }
    async getCustomCategories(): Promise<Array<CustomCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomCategories();
            return result;
        }
    }
    async getItems(arg0: bigint, arg1: boolean | null, arg2: BagFilter): Promise<Array<PackingItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getItems(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), to_candid_BagFilter_n9(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItems(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), to_candid_BagFilter_n9(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTemplateById(arg0: bigint): Promise<TemplateView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTemplateById(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTemplateById(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTemplates(): Promise<Array<TemplateView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTemplates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTemplates();
            return result;
        }
    }
    async getTripById(arg0: bigint): Promise<Trip | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTripById(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTripById(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTripWeather(arg0: bigint): Promise<CachedTripWeather | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTripWeather(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTripWeather(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrips(): Promise<Array<Trip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrips();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrips();
            return result;
        }
    }
    async saveAsTemplate(arg0: bigint, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAsTemplate(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAsTemplate(arg0, arg1, arg2);
            return result;
        }
    }
    async setProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProfile(arg0);
            return result;
        }
    }
    async setTripWeather(arg0: bigint, arg1: Array<CachedWeatherDay>, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTripWeather(arg0, to_candid_vec_n24(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTripWeather(arg0, to_candid_vec_n24(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async togglePacked(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.togglePacked(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.togglePacked(arg0);
            return result;
        }
    }
    async updateBag(arg0: bigint, arg1: string, arg2: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBag(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBag(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateCustomActivity(arg0: bigint, arg1: string, arg2: Array<SuggestedItem>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomActivity(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomActivity(arg0, arg1, arg2);
            return result;
        }
    }
    async updateCustomCategory(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomCategory(arg0, arg1);
            return result;
        }
    }
    async updateItem(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: bigint | null, arg5: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateItem(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateItem(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async updateTemplate(arg0: bigint, arg1: string, arg2: string, arg3: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTemplate(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTemplate(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateTrip(arg0: bigint, arg1: string, arg2: number, arg3: number, arg4: bigint, arg5: bigint, arg6: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTrip(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTrip(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
}
function from_candid_Bag_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Bag): Bag {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_CachedTripWeather_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CachedTripWeather): CachedTripWeather {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_CachedWeatherDay_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CachedWeatherDay): CachedWeatherDay {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_PackingItem_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PackingItem): PackingItem {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TemplateView]): TemplateView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Trip]): Trip | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CachedTripWeather]): CachedTripWeather | null {
    return value.length === 0 ? null : from_candid_CachedTripWeather_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    weight: [] | [bigint];
    name: string;
    quantity: bigint;
    category: string;
    bagId: [] | [bigint];
    packed: boolean;
    listId: bigint;
}): {
    id: bigint;
    weight?: bigint;
    name: string;
    quantity: bigint;
    category: string;
    bagId?: bigint;
    packed: boolean;
    listId: bigint;
} {
    return {
        id: value.id,
        weight: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.weight)),
        name: value.name,
        quantity: value.quantity,
        category: value.category,
        bagId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.bagId)),
        packed: value.packed,
        listId: value.listId
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    days: Array<_CachedWeatherDay>;
    tripId: bigint;
    cachedAt: bigint;
    hasHistoricalDays: boolean;
}): {
    days: Array<CachedWeatherDay>;
    tripId: bigint;
    cachedAt: bigint;
    hasHistoricalDays: boolean;
} {
    return {
        days: from_candid_vec_n20(_uploadFile, _downloadFile, value.days),
        tripId: value.tripId,
        cachedAt: value.cachedAt,
        hasHistoricalDays: value.hasHistoricalDays
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: string;
    tempMax: number;
    tempMin: number;
    isHistorical: boolean;
    weatherCode: bigint;
    precipitationSum: [] | [number];
    precipitationProbability: [] | [number];
}): {
    date: string;
    tempMax: number;
    tempMin: number;
    isHistorical: boolean;
    weatherCode: bigint;
    precipitationSum?: number;
    precipitationProbability?: number;
} {
    return {
        date: value.date,
        tempMax: value.tempMax,
        tempMin: value.tempMin,
        isHistorical: value.isHistorical,
        weatherCode: value.weatherCode,
        precipitationSum: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.precipitationSum)),
        precipitationProbability: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.precipitationProbability))
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    weightLimit: [] | [bigint];
    listId: bigint;
}): {
    id: bigint;
    name: string;
    weightLimit?: bigint;
    listId: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        weightLimit: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.weightLimit)),
        listId: value.listId
    };
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PackingItem>): Array<PackingItem> {
    return value.map((x)=>from_candid_PackingItem_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CachedWeatherDay>): Array<CachedWeatherDay> {
    return value.map((x)=>from_candid_CachedWeatherDay_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Bag>): Array<Bag> {
    return value.map((x)=>from_candid_Bag_n5(_uploadFile, _downloadFile, x));
}
function to_candid_BagFilter_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BagFilter): _BagFilter {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_CachedWeatherDay_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CachedWeatherDay): _CachedWeatherDay {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: boolean | null): [] | [boolean] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: string;
    tempMax: number;
    tempMin: number;
    isHistorical: boolean;
    weatherCode: bigint;
    precipitationSum?: number;
    precipitationProbability?: number;
}): {
    date: string;
    tempMax: number;
    tempMin: number;
    isHistorical: boolean;
    weatherCode: bigint;
    precipitationSum: [] | [number];
    precipitationProbability: [] | [number];
} {
    return {
        date: value.date,
        tempMax: value.tempMax,
        tempMin: value.tempMin,
        isHistorical: value.isHistorical,
        weatherCode: value.weatherCode,
        precipitationSum: value.precipitationSum ? candid_some(value.precipitationSum) : candid_none(),
        precipitationProbability: value.precipitationProbability ? candid_some(value.precipitationProbability) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weight?: bigint;
    name: string;
    quantity: bigint;
    category: string;
}): {
    weight: [] | [bigint];
    name: string;
    quantity: bigint;
    category: string;
} {
    return {
        weight: value.weight ? candid_some(value.weight) : candid_none(),
        name: value.name,
        quantity: value.quantity,
        category: value.category
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "all";
    all: null;
} | {
    __kind__: "specific";
    specific: bigint;
} | {
    __kind__: "unassigned";
    unassigned: null;
}): {
    all: null;
} | {
    specific: bigint;
} | {
    unassigned: null;
} {
    return value.__kind__ === "all" ? {
        all: value.all
    } : value.__kind__ === "specific" ? {
        specific: value.specific
    } : value.__kind__ === "unassigned" ? {
        unassigned: value.unassigned
    } : value;
}
function to_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<{
    weight?: bigint;
    name: string;
    quantity: bigint;
    category: string;
}>): Array<{
    weight: [] | [bigint];
    name: string;
    quantity: bigint;
    category: string;
}> {
    return value.map((x)=>to_candid_record_n3(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<CachedWeatherDay>): Array<_CachedWeatherDay> {
    return value.map((x)=>to_candid_CachedWeatherDay_n25(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
