/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SuggestedItem = IDL.Record({
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
});
export const Bag = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'weightLimit' : IDL.Opt(IDL.Nat),
  'listId' : IDL.Nat,
});
export const CustomActivity = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'suggestedItems' : IDL.Vec(SuggestedItem),
});
export const CustomCategory = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const BagFilter = IDL.Variant({
  'all' : IDL.Null,
  'specific' : IDL.Nat,
  'unassigned' : IDL.Null,
});
export const PackingItem = IDL.Record({
  'id' : IDL.Nat,
  'weight' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
  'bagId' : IDL.Opt(IDL.Nat),
  'packed' : IDL.Bool,
  'listId' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TemplateView = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'itemCount' : IDL.Nat,
  'activities' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'bagCount' : IDL.Nat,
});
export const Trip = IDL.Record({
  'id' : IDL.Nat,
  'latitude' : IDL.Float64,
  'destination' : IDL.Text,
  'endDate' : IDL.Int,
  'createdAt' : IDL.Int,
  'activities' : IDL.Vec(IDL.Text),
  'longitude' : IDL.Float64,
  'startDate' : IDL.Int,
});
export const CachedWeatherDay = IDL.Record({
  'date' : IDL.Text,
  'tempMax' : IDL.Float64,
  'tempMin' : IDL.Float64,
  'isHistorical' : IDL.Bool,
  'weatherCode' : IDL.Nat,
  'precipitationSum' : IDL.Opt(IDL.Float64),
  'precipitationProbability' : IDL.Opt(IDL.Float64),
});
export const CachedTripWeather = IDL.Record({
  'days' : IDL.Vec(CachedWeatherDay),
  'tripId' : IDL.Nat,
  'cachedAt' : IDL.Int,
  'hasHistoricalDays' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addItem' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Nat],
      [],
    ),
  'applyTemplate' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignToBag' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Nat)], [], []),
  'bulkAddItems' : IDL.Func(
      [
        IDL.Nat,
        IDL.Vec(
          IDL.Record({
            'weight' : IDL.Opt(IDL.Nat),
            'name' : IDL.Text,
            'quantity' : IDL.Nat,
            'category' : IDL.Text,
          })
        ),
      ],
      [IDL.Vec(IDL.Nat)],
      [],
    ),
  'clearTripWeather' : IDL.Func([IDL.Nat], [], []),
  'createBag' : IDL.Func([IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat)], [IDL.Nat], []),
  'createCustomActivity' : IDL.Func(
      [IDL.Text, IDL.Vec(SuggestedItem)],
      [IDL.Nat],
      [],
    ),
  'createCustomCategory' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'createTemplate' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'createTrip' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Int, IDL.Int, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'deleteBag' : IDL.Func([IDL.Nat], [], []),
  'deleteCustomActivity' : IDL.Func([IDL.Nat], [], []),
  'deleteCustomCategory' : IDL.Func([IDL.Nat], [], []),
  'deleteItem' : IDL.Func([IDL.Nat], [], []),
  'deleteTemplate' : IDL.Func([IDL.Nat], [], []),
  'deleteTrip' : IDL.Func([IDL.Nat], [], []),
  'getActivitySuggestedItems' : IDL.Func(
      [IDL.Vec(IDL.Nat)],
      [IDL.Vec(SuggestedItem)],
      ['query'],
    ),
  'getBags' : IDL.Func([IDL.Nat], [IDL.Vec(Bag)], ['query']),
  'getCustomActivities' : IDL.Func([], [IDL.Vec(CustomActivity)], ['query']),
  'getCustomCategories' : IDL.Func([], [IDL.Vec(CustomCategory)], ['query']),
  'getItems' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Bool), BagFilter],
      [IDL.Vec(PackingItem)],
      ['query'],
    ),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getTemplateById' : IDL.Func([IDL.Nat], [IDL.Opt(TemplateView)], ['query']),
  'getTemplates' : IDL.Func([], [IDL.Vec(TemplateView)], ['query']),
  'getTripById' : IDL.Func([IDL.Nat], [IDL.Opt(Trip)], ['query']),
  'getTripWeather' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(CachedTripWeather)],
      ['query'],
    ),
  'getTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
  'saveAsTemplate' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
  'setProfile' : IDL.Func([IDL.Text], [], []),
  'setTripWeather' : IDL.Func(
      [IDL.Nat, IDL.Vec(CachedWeatherDay), IDL.Bool],
      [],
      [],
    ),
  'togglePacked' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'updateBag' : IDL.Func([IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat)], [], []),
  'updateCustomActivity' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Vec(SuggestedItem)],
      [],
      [],
    ),
  'updateCustomCategory' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateItem' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
      ],
      [],
      [],
    ),
  'updateTemplate' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'updateTrip' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Int,
        IDL.Int,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SuggestedItem = IDL.Record({
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
  });
  const Bag = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'weightLimit' : IDL.Opt(IDL.Nat),
    'listId' : IDL.Nat,
  });
  const CustomActivity = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'suggestedItems' : IDL.Vec(SuggestedItem),
  });
  const CustomCategory = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const BagFilter = IDL.Variant({
    'all' : IDL.Null,
    'specific' : IDL.Nat,
    'unassigned' : IDL.Null,
  });
  const PackingItem = IDL.Record({
    'id' : IDL.Nat,
    'weight' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
    'bagId' : IDL.Opt(IDL.Nat),
    'packed' : IDL.Bool,
    'listId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TemplateView = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'itemCount' : IDL.Nat,
    'activities' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'bagCount' : IDL.Nat,
  });
  const Trip = IDL.Record({
    'id' : IDL.Nat,
    'latitude' : IDL.Float64,
    'destination' : IDL.Text,
    'endDate' : IDL.Int,
    'createdAt' : IDL.Int,
    'activities' : IDL.Vec(IDL.Text),
    'longitude' : IDL.Float64,
    'startDate' : IDL.Int,
  });
  const CachedWeatherDay = IDL.Record({
    'date' : IDL.Text,
    'tempMax' : IDL.Float64,
    'tempMin' : IDL.Float64,
    'isHistorical' : IDL.Bool,
    'weatherCode' : IDL.Nat,
    'precipitationSum' : IDL.Opt(IDL.Float64),
    'precipitationProbability' : IDL.Opt(IDL.Float64),
  });
  const CachedTripWeather = IDL.Record({
    'days' : IDL.Vec(CachedWeatherDay),
    'tripId' : IDL.Nat,
    'cachedAt' : IDL.Int,
    'hasHistoricalDays' : IDL.Bool,
  });
  
  return IDL.Service({
    'addItem' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Nat],
        [],
      ),
    'applyTemplate' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignToBag' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Nat)], [], []),
    'bulkAddItems' : IDL.Func(
        [
          IDL.Nat,
          IDL.Vec(
            IDL.Record({
              'weight' : IDL.Opt(IDL.Nat),
              'name' : IDL.Text,
              'quantity' : IDL.Nat,
              'category' : IDL.Text,
            })
          ),
        ],
        [IDL.Vec(IDL.Nat)],
        [],
      ),
    'clearTripWeather' : IDL.Func([IDL.Nat], [], []),
    'createBag' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'createCustomActivity' : IDL.Func(
        [IDL.Text, IDL.Vec(SuggestedItem)],
        [IDL.Nat],
        [],
      ),
    'createCustomCategory' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'createTemplate' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'createTrip' : IDL.Func(
        [
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Int,
          IDL.Int,
          IDL.Vec(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'deleteBag' : IDL.Func([IDL.Nat], [], []),
    'deleteCustomActivity' : IDL.Func([IDL.Nat], [], []),
    'deleteCustomCategory' : IDL.Func([IDL.Nat], [], []),
    'deleteItem' : IDL.Func([IDL.Nat], [], []),
    'deleteTemplate' : IDL.Func([IDL.Nat], [], []),
    'deleteTrip' : IDL.Func([IDL.Nat], [], []),
    'getActivitySuggestedItems' : IDL.Func(
        [IDL.Vec(IDL.Nat)],
        [IDL.Vec(SuggestedItem)],
        ['query'],
      ),
    'getBags' : IDL.Func([IDL.Nat], [IDL.Vec(Bag)], ['query']),
    'getCustomActivities' : IDL.Func([], [IDL.Vec(CustomActivity)], ['query']),
    'getCustomCategories' : IDL.Func([], [IDL.Vec(CustomCategory)], ['query']),
    'getItems' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Bool), BagFilter],
        [IDL.Vec(PackingItem)],
        ['query'],
      ),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getTemplateById' : IDL.Func([IDL.Nat], [IDL.Opt(TemplateView)], ['query']),
    'getTemplates' : IDL.Func([], [IDL.Vec(TemplateView)], ['query']),
    'getTripById' : IDL.Func([IDL.Nat], [IDL.Opt(Trip)], ['query']),
    'getTripWeather' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(CachedTripWeather)],
        ['query'],
      ),
    'getTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
    'saveAsTemplate' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
    'setProfile' : IDL.Func([IDL.Text], [], []),
    'setTripWeather' : IDL.Func(
        [IDL.Nat, IDL.Vec(CachedWeatherDay), IDL.Bool],
        [],
        [],
      ),
    'togglePacked' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'updateBag' : IDL.Func([IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat)], [], []),
    'updateCustomActivity' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Vec(SuggestedItem)],
        [],
        [],
      ),
    'updateCustomCategory' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateItem' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
        ],
        [],
        [],
      ),
    'updateTemplate' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'updateTrip' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Int,
          IDL.Int,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };