/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bag {
  'id' : bigint,
  'name' : string,
  'weightLimit' : [] | [bigint],
  'listId' : bigint,
}
export type BagFilter = { 'all' : null } |
  { 'specific' : bigint } |
  { 'unassigned' : null };
export interface CachedTripWeather {
  'days' : Array<CachedWeatherDay>,
  'tripId' : bigint,
  'cachedAt' : bigint,
  'hasHistoricalDays' : boolean,
}
export interface CachedWeatherDay {
  'date' : string,
  'tempMax' : number,
  'tempMin' : number,
  'isHistorical' : boolean,
  'weatherCode' : bigint,
  'precipitationSum' : [] | [number],
  'precipitationProbability' : [] | [number],
}
export interface CustomActivity {
  'id' : bigint,
  'name' : string,
  'suggestedItems' : Array<SuggestedItem>,
}
export interface CustomCategory { 'id' : bigint, 'name' : string }
export interface PackingItem {
  'id' : bigint,
  'weight' : [] | [bigint],
  'name' : string,
  'quantity' : bigint,
  'category' : string,
  'bagId' : [] | [bigint],
  'packed' : boolean,
  'listId' : bigint,
}
export interface SuggestedItem {
  'name' : string,
  'quantity' : bigint,
  'category' : string,
}
export interface TemplateView {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'itemCount' : bigint,
  'activities' : Array<string>,
  'description' : string,
  'bagCount' : bigint,
}
export interface Trip {
  'id' : bigint,
  'latitude' : number,
  'destination' : string,
  'endDate' : bigint,
  'createdAt' : bigint,
  'activities' : Array<string>,
  'longitude' : number,
  'startDate' : bigint,
}
export interface UserProfile { 'name' : string }
export interface _SERVICE {
  'addItem' : ActorMethod<
    [bigint, string, string, bigint, [] | [bigint], [] | [bigint]],
    bigint
  >,
  'applyTemplate' : ActorMethod<[bigint, bigint], undefined>,
  'assignToBag' : ActorMethod<[bigint, [] | [bigint]], undefined>,
  'bulkAddItems' : ActorMethod<
    [
      bigint,
      Array<
        {
          'weight' : [] | [bigint],
          'name' : string,
          'quantity' : bigint,
          'category' : string,
        }
      >,
    ],
    Array<bigint>
  >,
  'clearTripWeather' : ActorMethod<[bigint], undefined>,
  'createBag' : ActorMethod<[bigint, string, [] | [bigint]], bigint>,
  'createCustomActivity' : ActorMethod<[string, Array<SuggestedItem>], bigint>,
  'createCustomCategory' : ActorMethod<[string], bigint>,
  'createTemplate' : ActorMethod<[string, string, Array<string>], bigint>,
  'createTrip' : ActorMethod<
    [string, number, number, bigint, bigint, Array<string>],
    bigint
  >,
  'deleteBag' : ActorMethod<[bigint], undefined>,
  'deleteCustomActivity' : ActorMethod<[bigint], undefined>,
  'deleteCustomCategory' : ActorMethod<[bigint], undefined>,
  'deleteItem' : ActorMethod<[bigint], undefined>,
  'deleteTemplate' : ActorMethod<[bigint], undefined>,
  'deleteTrip' : ActorMethod<[bigint], undefined>,
  'getActivitySuggestedItems' : ActorMethod<
    [Array<bigint>],
    Array<SuggestedItem>
  >,
  'getBags' : ActorMethod<[bigint], Array<Bag>>,
  'getCustomActivities' : ActorMethod<[], Array<CustomActivity>>,
  'getCustomCategories' : ActorMethod<[], Array<CustomCategory>>,
  'getItems' : ActorMethod<
    [bigint, [] | [boolean], BagFilter],
    Array<PackingItem>
  >,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getTemplateById' : ActorMethod<[bigint], [] | [TemplateView]>,
  'getTemplates' : ActorMethod<[], Array<TemplateView>>,
  'getTripById' : ActorMethod<[bigint], [] | [Trip]>,
  'getTripWeather' : ActorMethod<[bigint], [] | [CachedTripWeather]>,
  'getTrips' : ActorMethod<[], Array<Trip>>,
  'saveAsTemplate' : ActorMethod<[bigint, string, string], bigint>,
  'setProfile' : ActorMethod<[string], undefined>,
  'setTripWeather' : ActorMethod<
    [bigint, Array<CachedWeatherDay>, boolean],
    undefined
  >,
  'togglePacked' : ActorMethod<[bigint], boolean>,
  'updateBag' : ActorMethod<[bigint, string, [] | [bigint]], undefined>,
  'updateCustomActivity' : ActorMethod<
    [bigint, string, Array<SuggestedItem>],
    undefined
  >,
  'updateCustomCategory' : ActorMethod<[bigint, string], undefined>,
  'updateItem' : ActorMethod<
    [bigint, string, string, bigint, [] | [bigint], [] | [bigint]],
    undefined
  >,
  'updateTemplate' : ActorMethod<
    [bigint, string, string, Array<string>],
    undefined
  >,
  'updateTrip' : ActorMethod<
    [bigint, string, number, number, bigint, bigint, Array<string>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];